FROM debian:latest
MAINTAINER drissi
RUN apt-get update && apt-get install -y libxml2-utils
ADD ScriptValidatorXMLandXSD.sh /home/ScriptValidatorXMLandXSD.sh
RUN chmod +x /home/ScriptValidatorXMLandXSD.sh